"""empty message

Revision ID: 36303c6d6b9e
Revises: 2ff35474301e
Create Date: 2020-03-03 16:24:24.210289

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '36303c6d6b9e'
down_revision = '2ff35474301e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('Artist', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('Artist', 'upcoming_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('Artist', 'seeking_venue',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.alter_column('Artist', 'past_shows',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
