"""empty message

Revision ID: 3d14c6bea8e3
Revises: 3a8a533c6d68
Create Date: 2020-03-02 09:56:30.116046

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d14c6bea8e3'
down_revision = '3a8a533c6d68'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('Show_artist_name_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_venue_name_fkey', 'Show', type_='foreignkey')
    op.drop_constraint('Show_artist_image_link_fkey', 'Show', type_='foreignkey')
    op.drop_column('Show', 'artist_image_link')
    op.drop_column('Show', 'id')
    op.drop_column('Show', 'artist_name')
    op.drop_column('Show', 'venue_name')
    op.add_column('Venue', sa.Column('past_shows_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'past_shows_count')
    op.add_column('Show', sa.Column('venue_name', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('Show', sa.Column('artist_name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('Show', sa.Column('id', sa.INTEGER(), server_default=sa.text('nextval(\'"Show_id_seq"\'::regclass)'), autoincrement=True, nullable=False))
    op.add_column('Show', sa.Column('artist_image_link', sa.VARCHAR(length=500), autoincrement=False, nullable=True))
    op.create_foreign_key('Show_artist_image_link_fkey', 'Show', 'Artist', ['artist_image_link'], ['image_link'])
    op.create_foreign_key('Show_venue_name_fkey', 'Show', 'Venue', ['venue_name'], ['name'])
    op.create_foreign_key('Show_artist_name_fkey', 'Show', 'Artist', ['artist_name'], ['name'])
    # ### end Alembic commands ###
