"""empty message

Revision ID: a5e159f3a212
Revises: 39d683933ba5
Create Date: 2020-03-06 15:32:48.372099

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e159f3a212'
down_revision = '39d683933ba5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Artist', sa.Column('created', sa.DateTime(), nullable=True))
    op.add_column('Venue', sa.Column('created', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Venue', 'created')
    op.drop_column('Artist', 'created')
    # ### end Alembic commands ###
